# Generated by Django 4.1.13 on 2024-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipousuario',
            name='fecha_de_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
